- name: job1
  command: "python ./examples/demo.py --value 1"
  num_gpus: 1

- name: job2
  command: "python ./examples/demo.py --value 2"
  num_gpus: 1

- name: job3
  command: "python ./examples/demo.py --value 3"
  num_gpus: 1

- name: job4
  command: "python ./examples/demo.py --value 4"
  num_gpus: 1

- name: job5
  command: "python ./examples/demo.py --value 5"
  num_gpus: 2
